"""Create glucose_levels table

Revision ID: 676f4b8d3d40
Revises: 
Create Date: 2025-03-12 11:15:13.528188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676f4b8d3d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glucose_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('glucose_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glucose_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glucose_levels_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glucose_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glucose_levels_user_id'))

    op.drop_table('glucose_levels')
    # ### end Alembic commands ###
