"""Create users_data table

Revision ID: 7f02a64dac04
Revises: 676f4b8d3d40
Create Date: 2025-03-12 13:06:27.929404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f02a64dac04'
down_revision = '676f4b8d3d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('Gerät', sa.String(), nullable=True),
    sa.Column('Seriennummer', sa.String(), nullable=True),
    sa.Column('Gerätezeitstempel', sa.String(), nullable=True),
    sa.Column('Aufzeichnungstyp', sa.String(), nullable=True),
    sa.Column('Glukosewert_Verlauf_mg_dL', sa.Float(), nullable=True),
    sa.Column('Glukose_Scan_mg_dL', sa.Float(), nullable=True),
    sa.Column('Nicht_numerisches_schnellwirkendes_Insulin', sa.String(), nullable=True),
    sa.Column('Schnellwirkendes_Insulin_Einheiten', sa.Float(), nullable=True),
    sa.Column('Nicht_numerische_Nahrungsdaten', sa.String(), nullable=True),
    sa.Column('Kohlenhydrate_Gramm', sa.Float(), nullable=True),
    sa.Column('Kohlenhydrate_Portionen', sa.Float(), nullable=True),
    sa.Column('Nicht_numerisches_Depotinsulin', sa.String(), nullable=True),
    sa.Column('Depotinsulin_Einheiten', sa.Float(), nullable=True),
    sa.Column('Notizen', sa.String(), nullable=True),
    sa.Column('Glukose_Teststreifen_mg_dL', sa.Float(), nullable=True),
    sa.Column('Keton_mmol_L', sa.Float(), nullable=True),
    sa.Column('Mahlzeiteninsulin_Einheiten', sa.Float(), nullable=True),
    sa.Column('Korrekturinsulin_Einheiten', sa.Float(), nullable=True),
    sa.Column('Insulin_Aenderung_durch_Anwender_Einheiten', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    with op.batch_alter_table('glucose_levels', schema=None) as batch_op:
        batch_op.drop_index('ix_glucose_levels_user_id')

    op.drop_table('glucose_levels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glucose_levels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('glucose_value', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glucose_levels', schema=None) as batch_op:
        batch_op.create_index('ix_glucose_levels_user_id', ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('Glukose-Werte,Erstellt am,25-02-2021 17:28 UTC,Erstellt von,aaa', sa.TEXT(), nullable=True)
    )
    op.drop_table('users_data')
    # ### end Alembic commands ###
